### ISSUE TITLE
Request layout change for "farm news" on desktop

### ISSUE THREAD

**Issue by RanchoMishmash** [felixgb/harleyfarms.github.io#5]
Would like image layout similar to other pages, eg:
![image](https://user-images.githubusercontent.com/19611944/37876871-f17022a0-3007-11e8-8309-45a13043daa9.png)
with just a title underneath or title and portion of text

Happy to commit to landscape images only as the initial image on a post (the image displayed on the home page of the "farm news" section), or to a certain sequence of landscape and portrait

**Comment by felixgb** [comment]
OK, this is done. One thing to note though is that all the blog post images are the same size, so they will not be "staggered" like the images on the rest of the pages. Future blog posts with with different sized images will be though.
